language: node_js
sudo: true
dist: trusty
node_js:
- '5.5'
branches:
  only:
  - master
  - "/^core\\/.+$/"
addons:
  firefox: latest
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
cache:
  directories:
  - node_modules
  - bower_components
install:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- du -sh ./node_modules ./bower_components/ || true
- npm config set spin false
- npm config set loglevel http
- npm install
- npm run update-webdriver
script:
- node_modules/.bin/gulp --env=production
- node_modules/.bin/karma start karma.conf.js
- node_modules/.bin/gulp start &
- sleep 3
- node_modules/.bin/protractor protractor.conf.js --browser=firefox
before_deploy:
- sh heroku/pre-deploy.sh
deploy:
  provider: heroku
  buildpack: nodejs
  strategy: git
  api_key:
    secure: k8r7wfrT3FO0lFMIsU/iJsKv+d5NeFfJTNPK5zu0n3eY3xobwBY4k6u0eU4/KZtei/P9UCwIg4LvpJkrx/HI3kfR7ekDQfUn2hVzTrKc6V8305wUVFevsEIkmNeZ5YpOTUlEiRh6T+TQD7/J1zzzUlJSaoteM8ks6Y4+yKq4zaddZEykci8eRt4TLz9XYpCdrGvGRK6lJgin0/oaBwiKmeN7JHoq84vI+MGnp/roRxdSF63VIoz9ptjxz7IaqSOhpthZiEmdB2g6aKtC775xSL9mEsxYe/B99LT1ccF25gFwekzR0hE5lxKfZvVickzL64yfZDQxZYxMSsH6noc5N0s2+Y6RGLB7EAiJK5gFpnPaWK9OW6hYNYjp7i6mMPIGWFQ6in7Kt1ey3ZPGMWD2mZqMshP8q28zOKykN9I/8DEAXbHSuWLk+Xfvm9RVSJ7Lje2l/YTfzNKYHz6ad7lie7Eu1OA7il/eiXz9gBk+t/uEySPYsw3zatvUfpvYJU1d04JS3IWjaC+2kI9sUa0iekbO8hxIa+CtSYl3rr767GQWr4XgKVh9qpnaEevCtRKANt9c9Zas0XbsZcXtuF+4UwGaSE5qPrj6NgRVkVOnzji+oYF1bpUaf1zOma6LxfUg80ccyjnOKY+MVrEV5pWqX6TVewhPfbu52/QA0oI+FE8=
  on:
    branch: core/heroku-deployment
  run:
  - rake hello
