language: node_js
sudo: true
dist: trusty
node_js:
- '5.5'
branches:
  only:
  - master
  - "/^core\\/.+$/"
addons:
  firefox: latest
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
cache:
  directories:
  - node_modules
  - bower_components
install:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- du -sh ./node_modules ./bower_components/ || true
- npm config set spin false
- npm config set loglevel http
- npm install
- npm run update-webdriver
  - node_modules/.bin/bower install
script:
- node_modules/.bin/gulp --env=production
- node_modules/.bin/karma start karma.conf.js
- node_modules/.bin/gulp start &
  - sleep 5
- node_modules/.bin/protractor protractor.conf.js --browser=firefox
before_deploy:
- chmod ugo+x heroku/pre-deploy.sh
deploy:
  provider: heroku
  buildpack: nodejs
  api_key:
    secure: SJ/doc/geqMcxYDS0hFj1Ytcdkmsre6skFb1xd/BBsP+UfudI1sJ0rVQT3qItA8GkbJKpOf5ZcZ3ljSjto1FAzk48NSribD0UY0IgbVKFmp27G39w4iKtk8K90cpKnHqKGxnd1z6VaVEXFDNus3wXADBrmbZIX6rKYgdlfrN4vBH/wMrZU1/qU3Oye591rwmRu5RPMaLTgVgBhVYuQe1MHbxnLvgOpHILthr9c5miXg+acINxYCui6MxtJ13zBuoPd2tTx1vQFx5Xj2N5BAJm6SXk8jAoLL2xem9vgHdfbgQb24XjlD12pYQIwyMORAK91iL5vduhPy3U+ISnTTL20ePww9KHyBJz/3lvdsZxvSglOXnsvTwir64BHcpDuCGLebOr7FbldZ9Pe7OVc26oNd1qY1e37pnQC2Yd0bW7G6EK3QtV+7Zq38rOAHUVKyzOE9W9FGegZ8Z1qu50NAXFfwdNVOeqJCPeo3DfLOje3cj8SXSxS4xTQZoNOw5R5JWrQ1LuVJGgLq0SY38ZJOJfpKCglNos88FyXXIqJXCyi6PvE6YRdSqrTydluhijjJZbVR4zuwZDkRdWMbNoagmCjqV9pc9n9thvCysxfrWAELjI1tNWTYwLYy1tmjravrr8Ri/jy9rh+HyLVdKlPpqVOVKzeAIgiAxQK54gcJkCIY=
  app: angular-see
  on: core/heroku-deployment
