language: node_js
sudo: true
node_js:
- '6'
branches:
  only:
  - master
  - "/^core\\/.+$/"
addons:
  firefox: latest
cache:
  directories:
  - node_modules
  - bower_components
install:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- du -sh ./node_modules ./bower_components/ || true
- npm config set spin false
- npm config set loglevel http
- npm install
- node_modules/.bin/bower install
- npm run update-webdriver
before_script:
- node_modules/.bin/gulp lint
- node_modules/.bin/gulp test:build
- node_modules/.bin/karma start karma.conf.js
script:
- node_modules/.bin/gulp --env=production
after_script:
- node_modules/.bin/gulp start &
- sleep 2
- node_modules/.bin/protractor protractor.conf.js --browser=firefox
deploy:
  provider: heroku
  api_key:
    secure: DVxz51ZfyEPp2YRwlLpWa0GH96/eb7fXRPzVLx8msamR3oRz3eS0xM7UBkNjQYaM9LxdzSxEuOOXX/TtCbCgRoj95/II2FliQd7s0eIDqr+Qddja21v3v5TVeuSINbZ7V7TIbk9yutEVVDcX+P1ON2CJNxbF8EGgXiL3iqjbqH0sykWHASOTavjOsFqcAaTVe5w29bNcAM0aqhXYrWNVGVi9Ds+wKqhOCXdYOWNzc6xmmqrCAnJ7lNgRVw3Tur5U4voHd6LzINFkwR17hjjmUsMev1qR16FX/mWrQeduSkwtuYm6jsMKT5mpVs2Z8EZsdpRsl+609+qtcNzl02HJlW5zNKki/Cz1Qn5+p/cMLfqgbHnp2c8AREDmGzJFOCstDzd8u0PQxdE8Rmrj0FWATtxJqdmaUCgTGb8bMJVIHSAx/mnINiYHJSsTHwD1yHG9Sdbgx3u5XJ8vXvBvw6UpQd7dvVQvTtM4CjZ9UL8Q1iUIJp8AeqRDOwK96xfYuccnE7ZPsEwyGTjMxhyIG+O/z9yvzDIrbqqQ+QV86e4jEBdm41TzXNwotoq3O4sg01rFgPVEzofeMlXxK90pm/jGXxAr8m5eOUQz+5xveGR5E8K0QbBoqZIUrB5AO2rpIIYxyCEgeQgv4cdleuRzsPuYWorO7r90MdDrMHymNqSyORs=
  app: angular-see
  on:
    repo: thiren/angular-seed
    branch: core/heroku-deployment
