language: node_js
sudo: true
node_js:
- '6'

branches:
  only:
  - master
  - "/^core\\/.+$/"

addons:
  firefox: latest
cache:
  directories:
  - node_modules
  - bower_components

install:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- du -sh ./node_modules ./bower_components/ || true
- npm config set spin false
- npm config set loglevel http
- npm install
- node_modules/.bin/bower install
- npm run update-webdriver

before_script:
- node_modules/.bin/gulp lint
- node_modules/.bin/gulp test:build
- node_modules/.bin/karma start karma.conf.js

script:
- node_modules/.bin/gulp --env=production

after_script:
- node_modules/.bin/gulp start &
- sleep 2
- node_modules/.bin/protractor protractor.conf.js --browser=firefox

deploy:
  provider: heroku
  buildpack: nodejs
  api_key:
    secure: bE6KnZGTbhnJinuctdIykFYM7Gq1BMaBNh3m8mjYv2AQrpcoJcH1sI+iHTYNZFnsjbqVCU9kDW8QtPynZhoSpfvbbRPrNzAYrC/Ixw+C6W624ogq7Yjj8HHrUywp1O3TCl3sxS1DETxnyutZ8xoilOby/LYUgjG7bcq+wrok35+UxDLt9nNFyfZn/CyKrg1E1voPak5bz95NVEKJQiYqsJGPQmUKkpVrwiiFM8SaZHdFTFG5UFcQ0XeZ+7Koym55U1k3ZI8kVbEhWArRvFcI/YL2evjepgYztLvI3ct0Q6Ugs+y4szUNca6AIJilHFiwnBWPUL6y/2e0iplg2q9tANT3yhNdhqSiH1JD5uOOxSTW6RnGoJLrHs51zUBUpqL6VcmsVdgvyAHBH6EdXXJgHsLYa6mleRrMenyU/tTDSp2A2Dqit6IiFSL2i8wChDJN/8KIefRmCsVlFJkBr8Xq3aGYgC+QlJNnlcuosa5Mg6OrEiKymLF1K/6PzB5WLc0UtuUYV9khcGJ3RT6rDi7dnqvc52uTQprOQ2PsXNypowliBSD/2bIKtER5SuSbHI4k4AS7aelhOD9xL8e90IbCBIF/1lNi49pCSalnkbo7hLiVJcqs0U8qfsxQ5EITwsJ92KQuD4KaWvGNlZ0z4z8bwBRv5H89869DFvlllUtkJnw=
  skip_cleanup: true
  app: angular-see
  on: core/heroku-deployment
